baseURL = 'https://rhuygen.github.io/plato-cgse-doc/'
languageCode = 'en-us'
title = 'The Common-EGSE Documentation'
theme = "ananke"
publishdir = "../docs"

[security]
enableInlineShortcodes = false

[security.exec]
allow = ["^dart-sass-embedded$", "^go$", "^npx$", "^postcss$", "^asciidoctor$"]
osEnv = ["(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|RUBYLIB)$"]

[security.funcs]
getenv = ["^HUGO_"]

[security.http]
methods = ["(?i)GET|POST"]
urls = [".*"]
