baseURL = 'https://rhuygen.github.io/plato-cgse-doc/'
languageCode = 'en-us'
title = 'The Common-EGSE Documentation'
theme = "ananke"
publishdir = "../docs"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[params]
  text_color = ""
  author = "Rik Huygen"
  favicon = ""
  site_logo = "images/cgse-logo-100x100.png"
  description = "The CGSE Documentation Site."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-gray"
  recent_posts_number = 4
  paginationSinglePost = true

[params.homepage]
    # Homepage splash section - ie the "We Help Business Grow" section
    show_splash_section_one = true
    splash_one_image = "images/IMG_0187.png"
    splash_one_heading = "We Help Business Grow"
    splash_one_paragraph = "Lorem ipsum dolor sit amet, et essent mediocritatem quo, choro volumus oporteat an mei. Numquam dolores mel eu, mea docendi omittantur et, mea ea duis erat. Elit melius cu ius. Per ex novum tantas putant, ei his nullam aliquam apeirian. Aeterno quaestio constituto sea an, no eum intellegat assueverit."
    splash_one_link_url = "team"
    splash_one_link_text = "Meet our team"

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/rikhuygen"

[[params.ananke_socials]]
name = "GitHub"
url = "https://github.com/rhuygen/plato-cgse-doc"

[[params.ananke_socials]]
name = "Slack"
url = "https://plato-rgo9834.slack.com"

[security]
enableInlineShortcodes = false

[security.exec]
allow = ["^dart-sass-embedded$", "^go$", "^npx$", "^postcss$", "^asciidoctor$"]
osEnv = ["(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|RUBYLIB)$"]

[security.funcs]
getenv = ["^HUGO_"]

[security.http]
methods = ["(?i)GET|POST"]
urls = [".*"]
