baseURL = 'https://ivs-kuleuven.github.io/plato-cgse-doc/'
languageCode = 'en-us'
title = 'The Common-EGSE Documentation'
theme = "ananke"
publishdir = "../docs"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[params]
  author = "Rik Huygen"
  favicon = ""
  text_color = ""
  site_logo = "images/cgse-logo-100x100.png"
  description = "The CGSE Documentation Site."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-gray"
  recent_posts_number = 5
  paginationSinglePost = true

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/rikhuygen"

[[params.ananke_socials]]
name = "GitHub"
url = "https://github.com/ivs-kuleuven/plato-cgse-doc"

[[params.ananke_socials]]
name = "Slack"
url = "https://plato-rgo9834.slack.com"

[security]
enableInlineShortcodes = false

[security.exec]
allow = ["^dart-sass-embedded$", "^go$", "^npx$", "^postcss$", "^asciidoctor$"]
osEnv = ["(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|RUBYLIB)$"]

[security.funcs]
getenv = ["^HUGO_"]

[security.http]
methods = ["(?i)GET|POST"]
urls = [".*"]
