== Changelog

12/02/2024 — 0.11::
* Added a warning that loading/submitting a Setup doesn't propagate this new Setup to all components in the system, see <<conf-setup>>

29/06/2023 — 0.10::
* Added table with N-FEE modes and their register values for PFM, see <<tab-n-fee-modes>>

28/06/2023 — 0.9::
* Added an appendix to explain the difference between GitHub issues, NCRs and PVS, see <<app-issue-ncr-pvs>>
* Added a section on actions on the Setup when a new camera arrives, see <<sec-new-camera>>. (This is taken from a technical note by Pierre PLATO-KUL-PL-TN-0022)
* updated CCD layout images in a TAB for EM and FM, see <<n-fee-operations>>.
* Added section on SFT analysis to section on Camera Switch ON, see <<camera-switch-on-off>>.
* minor editorial changes like fixing links, typos, minor rewording, etc.

20/06/2023 — v0.8::
* Added explanation about Camera Switch ON / OFF, see <<camera-switch-on-off>>

19/06/2023 — v0.7::
* bringing the commanding manual up-to-date with the current implementation of the Common-EGSE, the test scripts and the situation in the test houses.
** Section on the plato-test-prep repository has been removed (was Section 3.3)
** Data Acquisition: updates in all sections
** Configuration and Setups: updates in all sections
** Common-EGSE startup, shutdown and sleep: updates in all sections
** Utility functions: updates in all sections
** Operating the N-FEE: updates in all sections
** Operating the TCS EGSE: only editorial updates
** Operating the OGSE: updates in all sections
** Operating the tests, system states: only editorial changes
** Appendix A: removed unimplemented ALT mode for `ccd_side` and updated other commands with correct parameters
** Appendix B: updated commands for visited positions

* added a backlink to the CGSE Documentation web site for your convenience. It's at the top of the HTML page.

[%collapsible]
.Click to see older changelog entries
======
12/06/2023 — v0.6::
* move the commanding manual to the CGSE documentation page and converted into asciidoc.
* Update section on data structure

14/06/2021 — v0.5::
* Update section 11.3 (rem. col_end from BB signatures)

03/05/2021 — v0.4::
* Update sections 3.2, 3.3, 7.3, 7.4
* Sections 11.1 & 11.3 Change ccd_side & EF convention
* New sections 5.3, 6.3, 11.4 and 14
* Update sections 3.2, 3.3, 7.3, 7.4
* Sections 11.1 & 11.3 Change ccd_side  & EF convention
* New sections 5.3, 6.3, 11.4 and 14
======
