== Changelog

18/06/2023 — v1.4::
* added a backlink to the CGSE Documentation web site for your convenience. It's at the top of the HTML page.

09/02/2023 — v1.3::
* Added description for the PLATO_CAMERA_IS_EM environment variable, see <<setup-environment>>
* Added section on providing _sudo_ permissions to plato-data in the user administration, see <<user-admin>>.
* Added section about install and set up a node exporter dashboard, see <<node-exporter-install>>.
* Added info on the 'hosts' file, see <<etc-hosts>>.
* Small fixes and updates in several sections

20/01/2023 – v1.2::
* We will now try to maintain a changelog.
* Documented the installation and activation of a VNC Server on Ubuntu, see <<install-vnc>>
* Improved section on 'Setting up the environment', see <<setup-environment>>
* Updated the version numbering used for releases in update commands, see <<cgse-update>> and <<test-scripts-update>>
* Added info on how to set the terminal title, see <<set-terminal-title>>
* Added explanation of `--ignore-installed` optional argument for `pip`, see <<python-package-update>>
* Added a brief explanation on exporting a mount point on the egse-server <<export-mount-point>> and mounting the mount point <<mount>> on the egse-client.
