== Introduction

This guide explains the installation and configuration of the following components:

* The operating system (CentOS-8) on the `egse-server` and `egse-client` machines
* The installation of basic tools like git, Python
* The installation of the Common-EGSE (CGSE) <- `plato-common-egse`
* The installation of the Test Scripts (TS) <- `plato-test-scripts`
* The installation of the Configuration files (Setups) <- `plato-cgse-conf`

Please note there is a difference between an installation on an operational machine with respect to your development environment. The operational machine has in principle a __read-only__ installation. That means no files in the repositories shall be changed and it will not be possible to push any changes to the GitHub repositories from any operational machine. The development installation on your local laptop or desktop is an installation where you can have full control over your development. In this environment you make changes, test your code, document the code, update, merge, and push to your __origin__ repository, to end with a pull request from __origin__ to __upstream__ which is the official GitHub repo.

We will also spend some time in this manual on how to update your system for security updates and how to update the Common-EGSE and test-scripts with new releases.
