[#python-package-update]
== Update Python packages

Ideally, the installed third party packages should be the versions that are given the requirements file of the project. If the requirements file is updated, you can use the following command to update your installation:

----
$ cd $PLATO_COMMON_EGSE_PATH
$ python3 -m pip install --upgrade --prefix=/cgse -r requirements.txt  # <1> <2>
----
<1> note the `--prefix` to make sure the upgrade of the packages is done in the correct location and not in the system folders. Instead of `/cgse` you can also use `$PLATO_INSTALL_LOCATION` for the `--prefix` value.
<2> on Ubuntu, the system Python installation has packages installed in `/usr/lib/python3/dist-packages` and that location is not writable for the 'plato-data' user. When you get an error during installation, add the option `--ignore-installed` to the `pip` command.

To update the Python packages for the test scripts, make sure you are inside the virtual environment:

----
$ cd ~/git/plato-test-scripts
$ source venv/bin/activate  # <1>
$ python3 -m pip install --upgrade -r requirements.txt
----
<1> it's important that you are in the virtual environment before performing the upgrade, then the packages will be installed—as intended—in your virtual environment.
