== Update Python packages

Ideally, the installed third party packages should be the versions that are given the requirements file of the project. If the requirements file is updated, you can use the following command to update your installation:

----
$ cd $PLATO_COMMON_EGSE_PATH
$ python3 -m pip install --upgrade --target=/cgse/lib/python -r requirements.txt  # <1>
----
<1> note the `--target` to make sure the upgrade of the packages is done in the correct location and not in the system folders. You will have to specify the full absolute path to the location where the packages need to be installed. Specifying the `$PLATO_INSTALL_LOCATION` is not sufficient.

To update the Python packages for the test scripts, make sure you are inside the virtual environment:

----
$ cd ~/git/plato-test-scripts
$ source venv/bin/activate  # <1>
$ python3 -m pip install --upgrade -r requirements.txt
----
<1> it's important that you are in the virtual environment before performing the upgrade, then the packages will be installed —as intended— in your virtual environment.
