== Abstract

This document is the user manual for the PLATO Common-EGSE and Test Script. The software is used at CSL and the test houses at IAS, INTA and SRON. The document describes all user interactions with the different components of the Common-EGSE system and how to run the different test scripts to perform camera testing. The focus in this document is on _how to work with the system_, not on which tasks and commands you will have to execute to perform a test. The latter is described in full detail in the https://ivs-kuleuven.github.io/plato-cgse-doc/asciidocs/commanding-manual.html[Ground Tests Commanding Manual].

This manual assumes the system has been installed and is properly configured and will therefore not explain configuration settings nor installation procedures. Please refer to the link:installation-manual.html[installation manual] for this information.

The Common-EGSE framework and the Test Scripts are part of the PLATO Camera Alignment and Testing program. The software is developed in-house in the Python 3 programming language and runs on the Linux OS. The Common-EGSE is a distributed system with (micro-)services and controllers for hardware devices that make up the ground test equipment. Camera testing is performed by executing test scripts in a Python 3.8+ environment following the _as-run_ test procedures.
