== Frequently Asked Questions (FAQ)

=== How can I check the installed version of the CGSE and Test Scripts

Use the following commands in a terminal:
----
$ python3 -m egse.version
CGSE version in Settings: 2023.23.0+CGSE
CGSE git version = 2023.23.0+CGSE-9-g05a2f153
CGSE installed version = 2023.23.0+cgse
----
----
$ python3 -m camtest.version
CAMTEST version in Settings: 2023.23.0+TS
CAMTEST git version = 2023.23.0+TS-0-gadedfd8
----
NOTE::
The Common-EGSE is installed on both the egse-server and the egse-client and shall have the same version.

See the section xref:Update the Common-EGSE Software[] on how to get the latest version installed in your environment.

=== How do I check if all the devices have been connected properly and are active?

TBW

Process Manager GUI or from the terminal...

=== How do I check if the Storage Manager is running?

You can check this in a terminal with the following command:

----
$ sm_cs status
Storage Manager:
  Status: active
  Hostname: 172.20.10.3
  Monitoring port: 6101
  Commanding port: 6100
  Service port: 6102
  Storage location: /Users/rik/data/CSL/
  Registrations: ['obsid', 'CM', 'PM', 'SYN-HK', 'SYN']
----

If you need more information e.g. to debug which files are being used to save the observation data, add the `--full` option to the above command:

[%nowrap,source]
----
$ sm_cs status --full
Storage Manager:
  Status: active
  Hostname: 172.20.10.3
  Monitoring port: 6101
  Commanding port: 6100
  Service port: 6102
  Storage location: /Users/rik/data/CSL/
  Registrations: ['obsid', 'CM', 'PM', 'SYN-HK', 'SYN']
Filenames for all registered items:
  obsid      ->  [PosixPath('/Users/rik/data/CSL/obsid-table.txt')]
  CM         ->  [PosixPath('/Users/rik/data/CSL/daily/20220530/20220530_CSL_CM.csv')]
  PM         ->  [PosixPath('/Users/rik/data/CSL/daily/20220530/20220530_CSL_PM.csv')]
  SYN-HK     ->  [PosixPath('/Users/rik/data/CSL/daily/20220530/20220530_CSL_SYN-HK.csv')]
  SYN        ->  [PosixPath('/Users/rik/data/CSL/daily/20220530/20220530_CSL_SYN.csv')]
No observation is registered.
Total disk space: 931.547 GiB
Used disk space: 887.819 GiB (95.31%)
Free disk space: 43.728 GiB (4.69%)
----

More information can be found in the

=== How do I check if the Configuration Manager is running?

You can check this in a terminal with the following command:

----
$ cm_cs status
Configuration manager:
  Status: active
  Site ID: IAS
  No observation running
  Setup loaded: 00077
  Hostname: 192.168.0.251
  Monitoring port: 6001
  Commanding port: 6000
  Service port: 6002
----

=== How do I check if the Process Manager is running?

You can check this in a terminal with the following command:

----
$ pm_cs status
Process Manager:
  Status: active
  Hostname: 192.168.0.251
  Monitoring port: 6201
  Commanding port: 6200
  Service port: 6202
----

=== How do I check if the Synoptics Manager is running?

You can check this in a terminal with the following command:

----
$ syn_cs status
Synoptics Manager:
  Status: active
  Hostname: 192.168.0.251
  Monitoring port: 6205
  Commanding port: 6204
  Service port: 6206
----

=== How do I check if the Logger is running?

You can check this in a terminal with the following command:

----
$ log_cs status
----

=== Where can I find my test data?

TBW
