== Introduction


=== Different User Perspectives

* system administrator is responsible for installing the operating system, keeping the system secure, organise backups, monitor disk space, ...
* operator
* the test conductor executes the tests

=== Where do I start?

* Start the Process Manager GUI.
* Start the PyCharm to execute test scripts

=== Client vs. Server

==== What should run on the Server?
All processes should run on the server.  These are:

* The core services (Storage Manager, Configuration Manager, Process Manager, Synoptics Manager, and Logger), which are (re-)started automatically via `systemd`;
* All control servers (incl. device control servers, FDIR, alert manager);
* ALl file generation processes (FITS generation, FOV HK, and N-FEE HK).

These processes can be started in two different ways:

* From the PM UI (see the Sect. below), which is running on the client;
* Directly on the command line on the server.

==== What should run on the Client?

The following things should be started on the client:

* The test scripts (in a PyCharm session);
* All GUIs.  These can be started from the command line or from the PM UI.  Note that all processes (not GUIs) that are started from the PM UI are started on the server, not on the client.
