== TODO

* Try to go through it with a user hat on — what is a user? operator/developer/sysadmin?
** installation procedure: be clear about it, which installation is for the normal users/developers/sysadmins?
*** using modules or .bash_profile to set up the environment?
** Inspection of the Settings & local settings
*** python -m egse.settings
*** python -m egse.setup --use-cm
*** GUI ?
** starting the different core services:
*** core services: invoke start-core-egse for users & developers? Systemd for sysadmins
*** how to check if these core services have been started and are working properly?
**** invoke status-core-egse or status for individual core services, e.g. log_cs status
**** cm_cs status
* What about the GUIs of the core services?
** log_cs has no GUI yet-> yes it does, cutelog and Textualog
** sm_cs has no GUI yet
** cm_cs has a GUI cm_ui ⟶ can not start when cm_cs is not running
* dpu_cs
** should be able to run as a daemon server, be able to connect/reconnect to N-FEE when needed/requested
** start it in the background?

* What shall go into the UM and what in the DM?
* Installation for the user:
** git clone from the IvS-KULeuven repo
** `python setup.py develop`
** `python -m pip install -e .`
* What is the focus of the user with respect to CGSE?
** GUIs
* Status Overview of the System
** How can we see what is running/active/ready…
*** commandline
*** GUIs
