== Building Blocks

(((building block)))

- [x] what are building blocks?
- [x] why do we need them?
- [x] where do they live?
- [x] how are they implemented?
** only keyword argument
- [x] how are they executed?
** all keyword arguments must be explicitly provided -> explain why
- [ ] ((generate_command_sequence))()????
- [ ] need to be executed within an observation (between start_ and end_observation() or by execute()) to enforce the creation of a unique obsid.

A building block is a Python function implementing the commands corresponding to a logical entity within a test or denoting an entire test (called the “test-script”). The function is decorated with a `@building_block` and has several benifits and restrictions that will be explained in this section. A typical small building block is shown below:

[source, python]
----
@building_block
def set_trp1(temperature: float) -> None:
    """
    Set the temperature setpoint for TRP1.

    Args:
        temperature: Temperature setpoint for TRP1 [°C].

    Raises:
        If a task is already running in the TCS EGSE, an Abort is raised.
    """

    if is_task_running():
        raise Abort("Cannot change the TRP1 setpoint, a task is running on the TCS")

    tcs: TCSInterface = GlobalState.setup.gse.tcs.device
    tcs.set_parameter(name="ch1_tset", value=temperature)
    tcs.commit()
----

A building block can only run within the context of an ((observation)) and all the arguments need to be explicitly provided as keyword arguments. The reason for this is the concept of _explicit is better than implicit_  which definitely holds for commanding test equipment and certainly a million dollar PLATO Camera. The requirement to explicitly provide all arguments with their name reduces the chance for making errors and prevents changes in argument defaults. The above building block will therefore be executed as follows:

[source, python]
----
from camtest.commanding import tcs

start_observation("Configure the TCS EGSE")
...
tcs.set_trp1(temperature=-70.0)
...
end_observation()
----

All functions that result in a change in the systems behaviour or a change in the test equipment shall be decorated as a building block. Status functions and so-called getters usually are not building blocks.

Building blocks implement some safeguards, imposing a number of limitations on the code:

* Building blocks cannot be called recursively. Beware of building blocks calling other building blocks. Avoid too many layers. Avoid functions calling building blocks.

* At run time, the names and the values of every argument of a building block must be explicitly given, even if the argument is `None`. Building blocks with many parameters are hence strongly discouraged.

* Positional arguments are rejected in building blocks, all arguments must be specified as keyword arguments.

* All arguments must be given the default value None in the building block definition.

The building block concept is part of the PLATO Test Scripts and not of the Common-EGSE. All building blocks that are defined will therefore live in the `plato-test-scripts` repository, mostly in the `camtest.commanding` module. The `@building_block` decorator itself is defined in the module `camtest.core.exec`.

The building block decorator is defined as `def building_block(func: Callable) -> Callable:` which means the decorator must be used without brackets `()` or arguments. The function which is decorated must be defined with keyword only arguments that all have a default value of `None`.

The building block decorator performs the following actions and checks for the function at import time:

* the decorated function `func` is attributed as a building block, i.e. the `func` will get the attribute `BUILDING_BLOCK_FUNC` set to `True`. This is internally used in the `execute` function to ensure the executed function is a building block.

* the decorator will check if a YAML file exists with the definition of default keyword arguments. The location of the YAML file is fixed.

[NOTE]
.Possible future change
====
Consider putting building block defaults in one _defaults.yaml_ file located at the same location as the building block definition. That would create one file for all defaults at that location, instead of one file for each building block. What to do when two building blocks have identical names, but defined in a different module?
====

The building block decorator performs the following actions and checks for the function at runtime:

* check that no positional arguments are passed into the function,
* fill the default value for keyword arguments that were not passed into the function, provided the function has defaults,
* check if there are still missing arguments, required keyword arguments that have no default and are not provided in the call.

Then, before the function is actually called, the `start_building_block()` function is called. This will register the building block in the observation context and add the command to the command sequence in the GlobalState if this is a dry run. A corresponding `end_building_block()` will de-register the function from the observation context and the command sequence.

The overhead for a function decorated as a building block is about 350μs.
