== Caveats

Place general warnings here on topics where the user might make specific assumption on the code or the usage of the code.

=== Setup

. It's not a good idea to create keys with spaces and special characters, although it is allowed in a dictionary and it works without problems, the key will not be available as an attribute because it will violate the Python syntax.

    >>> from egse.setup import Setup
    >>> s = Setup()
    >>> s["a key with spaces"] = 42
    >>> print(s)
    NavigableDict
    └── a key with spaces: 42
    >>> s['a key with spaces']
    42
    >>> s.a key with spaces
      Input In [18]
        s.a key with spaces
            ^
    SyntaxError: invalid syntax

. When submitting a Setup to the configuration manager, the Setup is automatically pushed to the GitHub repository with the message provided with the `submit_setup()` function. No need anymore to create a pull request. There are however two thing to keep in mind here:
.. do not add a Setup manually to your ((PLATO_CONF_FILE_LOCATION)) or to the repository. That will invalidate the repo and the cache that is maintained by the configuration manager
.. you should do a git pull regularly on your local machine and also on the egse-client if the folder is not NFS mounted
