== Changelog

06/03/2024 — v1.10::
* Added a story about finding a left-open socket... see <<stories>>.

27/02/2024 — v1.9::
* Added part on _Essential Toolkit and Infratsructure Elements_, see <<essential-toolkit>> and <<infrastructure-elements>>.
* Added some more info on Setup in <<the-setup>>.

12/02/2024 — v1.8::
* Started a chapter on SpaceWire communication, see <<spacewire>>.
* Added a chapter on the notification system for control servers, see <<notification-for-cs>>.

18/06/2023 — v1.7::
* Added a section on setting up a development environment to contribute to the CGSE and/or TS, see <<set-up-dev-env>>.
* added a backlink to the CGSE Documentation web site for your convenience. It's at the top of the HTML page.

04/05/2023 — v1.6::
* Added explanation about data distribution and monitoring message queues used by the DPU Processor to publish information and data, see <<sut>>.
* Added some more meat into the description of the arguments for the `@dynamic_command` decorator, see <<_dynamic_command_decorator>>.
* Added an explanation of the communication with and commanding of the N-FEE in the inner loop of the DPUProcessor, see <<inner-loop>>.

03/04/2023 — v1.5::
* Added a section 'Services' in the Commanding Concepts section, see <<services>>.

12/03/2023 — v1.4::
* Added description of the arguments that can be used with the `@dynamic_command` decorator, see <<_dynamic_command_decorator>>.
* Added a section on creating multiple control servers for identical devices, see <<multiple-idential-devices>>.

09/02/2023 — v1.3::
* Updated section on version and release numbers, see <<version-numbers>>.
* Fixed some formatting issues in the CCD numbering section.
