[#_dynamic_commanding]
== Dynamic Commanding

Two of the requirements that were formulated when we started the analysis and design of the CGSE was that (1) it shouldn't be too difficult to implement device controllers and (2) the definition of the commands shall be done at one place only. So we started out with a design where the commands were defined in a YAML file (called the _command yaml file_) and the code would use this information to build the API for the device. That would make it —from the device developer point of view— rather easy to create the commanding interface for a new device. Unfortunately, the implementation was not that easy or straightforward. We are working in a client-server or even microservices environment which means the device commanding should be available on both the server side (what we call the Controller) and on the client side (what we call the Proxy).

Both the Controller and the Proxy will have to implement the same interface, but we didn't want to bother the developer with having to implement the interface twice. The Proxy (client) side should be easy, because it doesn't need any processing or device control, it only needs to forward the command and its arguments to the server to be executed and then wait for the response. On the server it is slightly more complicated since there we have to interact with a device that can be connected by Ethernet, USB, serial,... with many different commanding protocols.

We have currently two designs and implementations that handle dynamic commanding. The first implementation we came up with is the `@dynamic_interface` which is a decorator that is used on the methods in the device interface class. How this works is explained in the section below on <<_dynamic_interface_decorator>>. The latest implementation is the `@dynamic_command` which also decorates the interface methods, but does a lot more work with respect to command string generation and response processing. How this work is explained in <<_dynamic_command_decorator>>. We have also written up a section on the transition from the old implementation into the new dynamic command implementation. See <<_move_to_dynamic_command>>.

[#_dynamic_interface_decorator]
=== The Dynamic Interface Decorator

A `@dynamic_interface` decorator adds a private static variable to a function or method. The variable name that is attributed is `__dynamic_interface` and it is used as a marker on the function.

The static variable is used by the Proxy class to check if a method is meant to be overridden dynamically. The idea behind this is to loosen the contract of an abstract base class (ABC) into an interface. For an ABC, the abstract methods must be implemented at construction/initialization. This is not possible for the Proxy subclasses as they load their commands (i.e. methods) from the control server, and the method will be added to the Proxy interface after loading. Nevertheless, we like the interface already defined for auto-completion during development or interactive use.

When a Proxy subclass that implements an interface with methods decorated by the `@dynamic_interface` does overwrite one or more of the decorated methods statically, these methods will not be dynamically overwritten when loading the interface from the control server. A warning will be logged instead.

The methods of the Proxy sub-class are added by the base class method `load_commands()`. This method asks the control server to send all device command definitions. The control server replies with a dictionary of user-defined methods and their names as keys. The commands are attributed to the Proxy class as methods with the key as their method names, unless the attribute name already exists in the Proxy and is not decorated as a dynamic interface. The following code snippet demonstrates how the command methods are dynamic added/attributed to the Proxy class.

[source,python]
----
def _add_commands(self):
    for key in self._commands:
        if hasattr(self, key):
            attribute = getattr(self, key)
            if (
                isinstance(attribute, types.MethodType) and
                not hasattr(attribute, "__dynamic_interface")
            ):
                continue
        command = self._commands[key]
        new_method = MethodType(command.client_call, self)
        new_method = set_docstring(new_method, command)
        setattr(self, key, new_method)
----

The command from the dictionary is not just added as a new attribute of course (that would be too easy 😀). Instead, each command is defined as an instance of a client-server command class (`ClientServerCommand`). The ClientServerCommand has two methods `client_call()` and `server_call()` and —you guessed it— all the dynamically attached methods are the `client_call()` method for that command, but carrying the name of the command, i.e. the key in the dictionary.

// XXXXX: try to remember why we can not just do `setattr(self, command.client_call, self)` or even with a plain assignment. -> see https://stackoverflow.com/questions/47797661/python-types-methodtype

The `command.client_call` is a function, i.e. an unbound class method. We are now trying to associate this function with the class instance (`self`) of the Proxy sub-class. We need to create a method that is _bound_ to the class instance. Think of it as _binding_ the class instance to the first argument of the function (the `self` argument).

The `MethodType()` returns a new callable object that holds both the function and the instance, and if you call this object, its first argument is automatically bound to the `self` argument.

The `setattr(self, key, new_method)` can not be replaced by a plain assignment because the name of the method is a string and we can not do something like `self.key = new_method` because the method name would be `key`.

So, during the creation of the Proxy object, the command list is requested from the control server, and when the command is not already an attribute of the Proxy sub-class, its `client_call()` method is connected as a new method to the Proxy sub-class.

The `ClientServerCommand` class is defined in the module `egse.command` and the `client_call()` method does something like in the code snippet below. The arguments that are passed into the function are first validated. This validation is done against the input given in the _command yaml file_. Then a command execution object is created which is sent to the control server. The response from the server is returned.

[source,python]
----
def client_call(self, other, *args, **kwargs):
    try:
        self.validate_arguments(*args, **kwargs)
    except CommandError as e_ce:
        logger.error(str(e_ce))
        return None

    ce = CommandExecution(self, *args, **kwargs)
    return other.send(ce)
----

At the control server, the command execution is received by the Protocol class and the command and the given arguments are extracted. The Protocol then calls the `server_call()` method of the command with the arguments. The (simplified) code snippet below illustrates what happens in the `execute()` method of the Protocol class at the server. The `self` variable is the instance of the device protocol class.

[source,python]
----
def execute(self):
    ...
    ce = self.receive()
    cmd = ce.get_cmd()
    args = ce.get_args()
    kwargs = ce.get_kwargs()
    ...
    cmd.server_call(self, *args, **kwargs)
----

The `server_call()` now calls the method from the Controller class that was associated with the `ClientServerCommand` while parsing and processing the _command yaml file_. That method is called with the arguments passed into the command execution.

- [] make a graph illustrating the round-trip of the commanding chain.

[#_dynamic_command_decorator]
=== The Dynamic Command Decorator

One of the problems of the dynamic interface decorator is that during construction of the Proxy class, the control server must be contacted to request the list of commands, when this fails and the control server is not available, the Proxy is not functional. You will first get a warning log message of the following type:

[source%nowrap]
----
<Device>Proxy could not connect to its control server at tcp://localhost:6700. No commands have been loaded.
----

When you then try to execute a command, e.g. `puna_proxy.get_speed()`, it will result in a `NotImplementedError`. The reason is that the commands have not been loaded from the control server and therefore the default interface method is executed resulting in this error.

Mainly for this reason we have enhanced the dynamic commanding protocol with the `@dynamic_command` decorator. This decorator behaves differently on the client side (the Proxy) and the server side (the Controller). There is no need anymore to load the available commands from the control server, so, proxies for devices can be started when the control server is not yet running and will gracefully (re-)connect to the device when the control server becomes available.

NOTE:: add more description of what the decorator is, what happens behind the scenes, how it is perceived on the client and on the server side etc...

So, since the `@dynamic_command` is the successor of the `@dynamic_interface`, how do we refactor our code for this new commanding scheme. That will be explained in the next section.

[#_move_to_dynamic_command]
=== Update your code to use the @dynamic_command decorator

* Each method in the interface needs to be changed from a `@dynamic_interface` to a `@dynamic_command`. Remember the `@dynamic_interface` only marked the method with the `__dynamic_interface` attribute. The `@dynamic_command` defines the type of command, how the command string is contructed and how the response needs to be decoded. As an example, consider the `get_current_position()` method in the `HuberSMC9300Interface` class.

[source,python]
----
    @dynamic_interface
    def get_current_position(self, axis) -> float:
        """
        Returns the current position for this axis as a float.
        """
        raise NotImplementedError

----
The method takes an argument `axis` and returns the current position as a float. The implementation is found in the `HuberSMC9300Controller` class.

[source,python]
----
    def get_current_position(self, axis) -> float:
        cmd_string = cmd_q_pos.get_cmd_string(axis)
        retStr = self.huber.get_response(cmd_string)

        # The response will look like '<axis>:<retPos>;'
        # where <axis> is the axis number and <retPos> is the current position
        # as a float
        retPos = float(retStr[2:-1])

        return retPos
----
In the new scheme, the method in the interface class will look like below and the method in the controller class will be removed.
[source,python]
----
    @dynamic_command(cmd_type="query", cmd_string="?p${axis}",
                     process_cmd_string=process_cmd_string,
                     process_response=decode_axis_float)
    def get_current_position(self, axis: int) -> float:
        """
        Returns the current position for this axis as a float.
        """
        raise NotImplementedError
----
The command is a _query_ command and therefore expects a response from the device. The command string is given in the form of a string template where 'axis' is replaced by the value of the `axis` argument of the method. The cmd_string will become `"?p1"` when `axis=1`. The `process_cmd_string` is a function that will prepare the command string for sending to the device. In the case of the HUBER stages, it appends `\r\n` before sending.

The `decode_axis_float` is a function used to decode the response from the device. It's a function that can be used to process all responses in the form of `<axis>:<float>;`.
[source,python]
----
def decode_axis_float(response: bytes) -> float:
    """
    Decodes the response of type '<axis>:<float>;' and strips off the newline.
    """

    response = response.decode().rstrip()

    return float(response[2:-1])
----
So, we removed the method from the _Controller_ class and converted the _Interface_ method from a `@dynamic_interface` to a `@dynamic_command`.
The _Controller_ class still inherits from the _Interface_ class, but additionally it now also needs to inherit from the `DynamicCommandMixin` class which is defined in the `egse.mixin` module.

[source,python]
----
    class HuberSMC9300Controller(HuberSMC9300Interface, DynamicCommandMixin):
        ...
----

* The Proxy class needs to inherit from `DynamicProxy` instead of `Proxy:

[source,python]
----
    class HuberSMC9300Proxy(DynamicProxy, HuberSMC9300Interface):
        ...
----

* Finally, remove all device command definitions from the device YAML file, in our case `smc9300.yaml`.

Thus far we have touch on the following arguments that can be used with `@dynamic_command`.

* `cmd_type` can be one of the following 'read', 'write', 'transaction', and 'query'. This is the only required argument for the decorator.

* `cmd_string` defines the formatting of the eventual command string that will be passed to the transport functions. The `cmd_string` is a template string that contains `$`-based substitutions for the function arguments. When you specify the `use_format=True` keyword, the `cmd_string` will be formatted using the format() function instead of the template substitution. The format option is less secure, but provides the functionality to format the arguments.
+
A template string looks like:
+
    cmd_string="CREATE:SENS:TEMP ${name} ${type} default=${default}"
+
The same `cmd_string` as a format option:
+
    cmd_string="CREATE:SENS:TEMP {name} {type} default={default:0.4f}"
    use_format=True

* `process_response` is a pure functionfootnote:[A pure function is a function that has no side effects and always returns the same output for the same input.] to process the response from the device before it is returned. This function shall take at least one keyword argument `response=` which is the response from the device as a byte array. The value that is returned by the function is eventually also the response of the command that was executed. This return value is device implementation specific and part of the interface definition.

* `process_cmd_string` is a pure function to process the given command string to make it ready for sending to the device. This function is called after the arguments to the command have been filled into the template string given by `cmd_string`. The function shall take a string as the only positional argument and return a string that will be sent to the device.

Then, there are these additional arguments that can be used with `@dynamic_command` to tune the command string and pre- and post-processing.

* `use_format` defines if the `cmd_str` shall be formatted as a template string or with the `format()` method.

* `process_kwargs` is a function that processes the keyword arguments and returns a string representation of those arguments. By default, keyword arguments are expanded in a string containing `key=value` pairs separated by spaces. This function is used when the arguments are given as `**kwargs` to the function definition.

* `pre_cmd` specifies a function that will be executed before the processed command string is sent to the device.

* `post_cmd` specifies a function that will be executed after the command is executed, i.e. sent to the device and potentially retrieved a response.

The `pre_cmd` and `post_cmd` keywords specify a callable/function to be executed before and/or after the actual command was executed. These functions are called with specific keyword arguments that allow additional device interaction and response processing. The `pre_cmd` function is called with the keyword argument `transport=` which passes the device transport. This allows the function to interact with the device again through the methods defined by the DeviceTransport interface. Additionally, the name of the called function (`function_name`), the processed command string (`cmd_string`) and the original positional (`args`) and keyword arguments (`kwargs`) are passed into the `pre_cmd` function. These additional arguments should not be changed, but can be used by the function for processing, logging, etc. The `pre_cmd` function must not return anything.

The `post_cmd` function is called with the keyword arguments `transport=` and `response=`. The response argument contains the response from the command that was previously sent to the device. The `post_cmd` function can use this response to parse its content and act against this content, although possible, it is usually not a good idea to alter the content of the response argument. The `post_cmd` function shall return (i.e. pass through) the response or return it's own information e.g. a status that was retrieved from the device with an additional command sent over transport.


We now have walked through all the steps to upgrade your device commanding. The next thing to do is testing!
