[glossary]
== Terminology

[glossary]
building block::
    A special function in the test scripts that must be executed within the context of an observation. Building blocks have special restrictions on arguments too, see XXXXX.
Core EGSE::
    Five services are considered core services: logger, configuration control, storage, processes, and synoptic monitoring.
control server::
    A server that provide control to a device or one of the core services.
EAFP::
    it’s Easier to Ask for Forgiveness than Permission
GlobalState::
    Defines the state of the system at the current time. Don't use this in the CGSE code, this is intended for test scripts and building blocks.
LBYL::
    Look Before You Leap
Observation::
    A top level building block that is executed directly from the REPL.
Proxy::
    XXXXX
Protocol::
    XXXXX
service::
    A service is provided usually by a server which supports specific functionality such as e.g. storage of data, or configuration control services. Often the Core EGSE control servers and the service they provide are used interchanged.
