== Introduction

This document is the developer guide for the PLATO Common-EGSE, used at CSL and the test houses at IAS, INTA and SRON and describes the Common-EGSE system from the developer's point of view. This document explains how to contribute to the code, which versions of libraries that are used, compiler options for device libraries written in C, access to the GitHub repo, coding style,and much more.

The current release contains 303 Python files, together they contain 95389 lines of which there are 49360 lines of Python code. About 50% of the code files contain actual code, the rest is documentation, comments and blank lines. It is impossible for one person to fully understand all details of the system and only for that reason is it essential to have good and comprehensive documentation.

Please, read the link:installation-manual.html[installation instructions] to know how to install the software and configure your Python installation.  Everything you need to know to be able to use the software is explained [here](../using-code/overview.md).  Before contributing to the code, read the instructions on how to do this [here](../contributing-code/overview.md).
