== Response, Failure, Success

The `control.py` module defines a number of classes that can be used to send a response on a device command to the client. Responses are handle by the `Protocol` class in the `handle_device_method()` method.

The main reason why these classes are provided is because Exceptions that happen in the server process should somehow propagate to the client process. A `Response` object can contain a return value if the command was executed successfully, or it can contain an Exception object when the device command has failed. If the command has failed or not can be checked by the client with the `successful()` method.

The `Response` class has three sub-classes, `Success`, `Failure`, and `Message`. A `Success` object is returned by the server process with the actual response in the property `return_code`. In the case of an Exception, the server process logs the error message and packs the Exception object in a `Failure` object.

XXXXX: insert a class diagram of Response and it's three sub-classes here
