== Code Reviews

WARNING: __This section is not finished and needs further updates. Please send me any comments and suggestions for improvement. Thanks, Rik.__

This is a proposal for a software source code review for the Common-EGSE. Code review is in principle a continuing process. With every pull request in GitHub there should be one of your colleagues doing a quick review of your changes before they are accepted and merged. We will add a section in xref:../contributing-code/pull-requests.md[Contributing to the Code > Pull Requests] explaining how to review the code changes from a pull request.

This section handles a slightly more formal code review that is required at certain milestones in the development process.

We will have a code review at TBD week.

The code review is done primarily for the following reasons:

* Share knowledge: you write code for yourself, your colleagues, test operators, scientists and engineers. Each of them should have a certain understanding of the system, but not all at the same detail.
* Maintainability: code should be understandable and at least two developers should know what the code does and why. These two developers are you and one of your colleagues.
* Finding bugs and design flaws.
* Consistent error and exception handling.
* Consistent logging.
* Finding functionality creep.
* Proper testing: test coverage, functionality testing.
* Development Principles: SOLID, DRY.
* Meet coding standards.

Please remember that the purpose of the code review is **not to reject** the code, but **to improve** the code quality. Focus is on how easy it is to understand the code.


=== Who is part of this Code Review?

Developers: Rik Huygen, Sara Regibo, ...

Instrument Experts: Pierre Royer, Bart Vandenbussche

Do we need more reviewers? The EGSE engineers from INTA and SRON? Somebody from the PCOT?


=== Planning

For each reviewer I will prepare an issue where you can check off the parts which have been reviewed. WHERE TO PUT THE REVIEW REPORTS/COMMENTS?

It is very important that the review is done in a timely fashion. We don't want to be bothered with this for weeks.

Proposal for reviewer/review items:

Sara Regibo:

* [ ] Commanding Concept

Nicolas Beraud:

* [ ] Hexapod package
* [ ] Stages package

Rik Huygen:

* [ ] Image Viewer
* [ ] Powermeter
* [ ] Shutter

Pierre Royer:

* [ ] GlobalState
* [ ] Setup

Bart Vandenbussche:

* [ ] Image Viewer functionality


=== What needs to be reviewed?

TODO: Make a checklist!

* **documentation**:

    ** API documentation at https://ivs-kuleuven.github.io/plato-common-egse/api/egse/[GitHub.io]

* **docstrings**: Do you understand from the docstring of the functions and public methods what the functionality is, what is needed as input and what is returned, if we need to catch exceptions?

* **coding style**: Do I understand what the code does, is the control flow not too complicated, ...

* **whatch-outs**:

  ** mutable default parameters

Be constructive! +
Be specific!

The goal is to ship good and maintainable code, it's not the goal to prove how good or clever we are.


=== Prerequisites

Before the code review, all the code will be run through a number of automated steps:

* check for trailing white space;
* check for end of file blank lines;
* check format of the YAML files;
* run the code through https://black.readthedocs.io/en/stable/[black] to make sure we have a consistent formatting;
* run the code through https://flake8.pycqa.org/en/latest/[flake8] to make sure the style guide is being followed;
* run all  the test harnesses, preferably with hardware attached, but also with the simulators. Have the test coverage report ready.

There will be a specific release for the code review with tag `code-review-2020-Q2`.
