==	System Summary

=== Version numbers

The version of Python that you use to run the code shall be asciimath:[>=] 3.8. You can determine the version of Python with the following terminal command:

----
$ python -V
Python 3.8.3
----

The version of the Common-EGSE and the test scripts that are installed on your system can be determined as follows:

----
python -m egse.version
CGSE git version = 2022.2.17-IAS-CGSE-53-ge5c9bc86
CGSE installed version = 2022.2.17-IAS-CGSE

python -m camtest.version
CAMTEST git version = 2022.2.1-IAS-TS-19-gd739137
----

The version numbers that are shown above have different parts that all have their meaning. Let's use the CGSE git version [`2022.2.17-IAS-CGSE-53-ge5c9bc86`] to explain each of the parts:

* `2022.2.17` is the usual semantic versioning with `major.minor.patch` numbers. The major number is the year in which the software was released. The minor number is increased with functionality changes or when a new test phase starts. The patch is used for urgent bug fixes.
* `IAS` is the site for which the release is distributed or created. We can have the same semantic version for one or more sites.
* `CGSE` is a release for the Common-EGSE repository. The Test scripts will have `TS` here.
* `53` is the number of commits that have been pushed and merged to the GitHub repository since the creation of the release. This number shall be 0 at least for the CGSE on an operational system. If stem:[!=] 0 as in the example above, it means you have not installed the release properly as explained in section XXXXX and you are probably using a development version with less tested or even un-tested code. This number can differ from 0 for the test scripts as we do not yet have a proper installation procedure for the releases.
* `ge5c9bc86` is the abbreviated git hash numberfootnote:[The full git hash is a much longer number and is an SHA-1 hash — a checksum of the content of the commit plus a header.] for this release. The first letter `g` indicates the use of `git`.

The VERSION and RELEASE are also defined in the `settings.yaml` and should match the first three parts of the version number explained above. If not, it was probably forgotten to update these numbers when preparing the release. You can use these number in your code by importing from `egse.version`. XXXXX: this is not the case yet for `camtest.version`!

----
from egse.version import VERSION
from egse.version import RELEASE
----
