==	The System Under Test (SUT)

- [x] Commanding is the same as all other devices, DPU Control Server and Controller, Proxy, etc
- [x] DPU Processor as a separate process to communicate to the FEE (Simulator)
- [x] DPU Protocol starts the DPU Processor process
- [x] DPU Controller and DPU Processor communicate via three Queues, the command queue, the response queue, and a priority queue.
- [x] Timing: timecode packet, HK packet, [Data packets], Commanding through RMAP requests
- [ ] Describe the transport

=== DPU Control Server and DPU Processor

The DPU Control Server (used to be called the DPU Simulator in older documents) acts like any other control server. It's Protocol class (`DPUProtocol`) starts a `DPUController` which implements the commands that are defined in the `DPUInterface` class. Specific DPU commands are sent to the control server using the `DPUProxy` class. The `DPUProxy` class also implements the `DPUInterface`.

The difference with normal device control servers lies in the additional sub-process which handles the communication with the N-FEE. This separate process, the `DPUProcessor`, is also started by the `DPUProtocol` and both the `DPUProcessor` and the `DPUController` communicate via three multiprocessing Queues, the command queue, the response queue, and a priority queue. The main task of the `DPUProcessor` is to communicate with the N-FEE, i.e. command it via SpaceWire RMAP Requests and retrieve housekeeping and data packets that are sent to the Storage manager. The command are passed by the `DPUController` through the command queue. Every readout cycle the `DPUProcessor` checks the command queue and passes any available command to the N-FEE as RMAP Requests.

Commands that are given on the Python prompt are by definition synchronous meaning when you call a function or execute a building block, the function or building block will wait for its return value before finishing. This is usually not a problem, because we most of the time have a pretty good idea how long a calculation or action will take. Most functions return within a few hundred milliseconds or less, which is practically immediate. When commanding the N-FEE however, things are more complicated. The N-FEE has strict timing when it comes to commanding. During the sync period (usually 6.25s unless commanded different) there is a slot of at least 2s at the end of the period, which is reserved for commanding. The sync period starts with a timecode packet followed by the N-FEE housekeeping packet. That takes just a few milliseconds. Depending on the N-FEE mode, we can then expect data packets filling up until 4s after the time code. There can be less or no data packets, leaving more time for commanding. Commanding the N-FEE is done by sending SpaceWire RMAP requests to the N-FEE in that 2s+ timeslot. When we send a command from the Python prompt to the N-FEE, it arrives in the command queue at the `DPUProcessor` and will be sent to the N-FEE in the next 2s+ command timeslot. When the Command enters the Queue at the beginning of the readout period, i.e. right after the timecode, maximum 4s will pass before the command is actually send to and executed on the N-FEE. All this time, the Python prompt will be blocked while waiting for the response. The next command can only be sent on return of the previous. So, we have two issues to solve, (1) the duration and blocking of all the steps in the commanding chain, and (2) sending more than just one command to the N-FEE in the same timeslot.

XXXXX: add here how we solved this!

The priority queue is also a command queue, but the commands are not sent to the N-FEE. Instead, the commands are executed in the `DPUProcessor` and are used to either get information about the state of the N-FEE or set/get the internal state of the `DPUProcessor`.  The state of the N-FEE is mirrored and kept up-to-date by the `DPUProcessor` during the readout cycle. Priority commands are typically to request e.g. the N-FEE mode, or to set an internal DPU parameter. While the command queue is checked only during the allowed RMAP communication period, the priority queue is checked and executed several times during the readout cycle.

=== The N-FEE Simulator

TBW

include::ccd-numbering.adoc[leveloffset=1]
