== The Synoptics Manager

_Synoptics_ = in a form of a summary or synopsis; taking or involving a comprehensive mental view. According to the Oxford Dictionary.

* what is this?
* Which parameters are Synoptic?
* From the device to the Grafana screen, what is the data flow, where are the name changes, where are the calibrations….

In all involved test facilities, the EGSE is used to perform the same set of basic operations: monitoring temperatures, changing the intensity of the source and point it somewhere, acquiring images, etc.  However, the devices that are used to perform these tasks are not everywhere the same (e.g. the OGSE with its lamp and filterwheels, the DAQs for temperature acquisition, etc.).

Each (device) control server has a dedicated CSV file in which the housekeeping information is stored and often the name of the parameters indicates the test facility at which they were acquired.

It is not inconvenient if user need to memorise the HK names for all test facilities, it also makes the test and analysis scripts more complex.

The Synoptics Manager stores this information in one centralised location (the synoptics file) with generic parameter names.

=== Synoptical Parameters

The housekeeping parameters that are stored in the synoptics are:

* Calibrated temperatures, acquired by the FEE, TCS, and facility DAQs;
* OGSE information (source intensity, measured power, whether the lamp and/or the laser are on);
* Source position, both actual and commanded, as field angles (θ,φ).

include::tm-dictionary.adoc[leveloffset=1]
