== Terminal Commands

A lot of testing and monitoring can be done from the command terminal and doesn't need a specific GUI or PyCharm. This section will explain how to check status of most of the control servers, how to inspect log files and HDF5 files, how to generate reports and how you can update the Common-EGSE and the test scripts.

=== What goes into this section

* See cheatsheet CGSE  → included below
* describe all _cs commands and their options, when to use them and when NOT to use them
* describe all _ui commands and their options
* what other terminal commands are used
** ps -ef|grep _cs
** kill PID or %1
** python -m egse (and all the other info modules)
** python ../src/scripts/check_hdf5_files.py
** python ../src/scripts/create_hdf5_report.py
** export_grafana_dashboards
** update_cgse → should become `cgse update`
** update_ts → should become `ts update`
* often used git commands
** git status
** git describe —tags
** git stash [pop]
** git fetch update
** git rebase update/develop
* Textualog, see xref:The Log Manager[]

<<<

image::cgse-cheat-sheet.pdf[height=80%]
