== Testing device Interfaces

The first step in the development of a device driver is to implement the direct interface to the device, e.g. the Ethernet or USB interface. In parallel to this step start implementing the simulator

There are several ways to test device interfaces since we have layered access to the devices. The direct access to a device is usually implemented in a `<device_name>_devif.py` module. If the device has an Ethernet connection, the class is usually called `<device_name>EthernetInterface`, e.g. `OGSEEthernetInterface`, for USB connected devices this would be `<device_name>USBInterface`, e.g. PM100AUSBInterface`.

When you have direct access to the device and it is not used in an operational environment, you can test the interface from the `Controller` class by directly instantiating this class and communicate with the device. If the device is used in an operation environment, you will benefit a lot if you have a simple simulator.

XXXXX - write a section on how to develop a simple instrument simulator. Take as an example OGSE and ...
