[discrete]
== List of TODO topics

* [ ] List the terminal commands in a simple overview table or something
* [ ] Explain System Preferences in the settings.yaml file (and the local settings)
* [ ] The Logger uses ZeroMQ to pass messages. That means these this ZeroMQ needs to be closed when your application ends.
* [ ] Where do we descibe the Synoptics Manager, where does this process fit into the design fiures etc.
* [ ] Somewhere we need to describe all the modules in the CGSE. For example, the `device.py` module defines a lot of interesting classes, including Exceptions, the device connection interfaces, and the device transport.
* [ ] Somewhere it shall be clearly explained where all these processes need to be started, on the egse-server or egse-client, manually or by Systemd, ... or clicking an icon?
* [ ] Should we maybe divide the developer manual in part 1 with coding advice and part 2 with the description of the CGSE code?
* [ ] Explain how the Failure — Success — Response classes work
* [ ] Explain how you can run the GUIs and even some control servers on your local machine using port forwarding. As an example, use the TCS or the Hexapod. This is only for hardware device connections, it is not for core services, run them as normal on your local machine.
* [ ] Find better names for the Parts in the manual
* [ ] WHere do we discuss devices with Ethernet interfaces and USB interfaces, the differences, the pros and cons, are there other still in use, like GPIO?
* [ ] Describe how to detect which process is holding a connection on Linux and macOS. This happens sometimes when a process crashes or when the developer did not properly close all connection, or when a process is hanging. You will get a `OSError: [Errno 48] Address already in use`.
