== Conventions used in this Book

We try to be consistent with the following typographical conventions:

Italic::
Indicates a new term or ...

Constant width::
Used for code listings, as well as within paragraphs to refer to program elements like variable and function names, data type, environment variables (`ALL_CAPS`), statements and keywords.

Constant width between angle brackets `<text>`::
Indicates `text` that should be replaced with user-supplied values or by values determined by context. The brackets should thereby be omitted.

When you see a `$ ...` in code listings, this is a command you need to execute in a terminal (omitting the dollar sign itself). When you see `>>> ...` in code listings, that is a Python expression that you need to execute in a Python REPL (here omitting the three brackets).

Setup versus setup::
I make a distinction between Setup (with a capital C) and setup (with a small c). The Setup is used when I talk about the object as defined in a Python environment, i.e. the entity itself that contains all the definitions, configuration and calibration parameters of the equipment that make up the complete test setup (notice the small letter 'c' here).
+
(sometimes you may find setup in the document which really should be 'set up')
